# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pcapqt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os


def resource_path(relative_path):
    """Get absolute path to resource, works for dev and PyInstaller exe"""
    if hasattr(sys, '_MEIPASS'):
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)


class Ui_PcapQt(object):
    def setupUi(self, PcapQt):
        PcapQt.setObjectName("PcapQt")
        PcapQt.setEnabled(True)
        PcapQt.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PcapQt.sizePolicy().hasHeightForWidth())
        PcapQt.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(PcapQt)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startCapture = QtWidgets.QPushButton(self.centralwidget)
        self.startCapture.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("icons/start-button.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(resource_path("icons/stop-button.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.startCapture.setIcon(icon)
        self.startCapture.setIconSize(QtCore.QSize(16, 16))
        self.startCapture.setCheckable(True)
        self.startCapture.setChecked(False)
        self.startCapture.setObjectName("startCapture")
        self.horizontalLayout.addWidget(self.startCapture)
        self.restartButton = QtWidgets.QPushButton(self.centralwidget)
        self.restartButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("icons/restart-button.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartButton.setIcon(icon1)
        self.restartButton.setObjectName("restartButton")
        self.horizontalLayout.addWidget(self.restartButton)
        self.detailButton = QtWidgets.QPushButton(self.centralwidget)
        self.detailButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("icons/detail.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailButton.setIcon(icon2)
        self.detailButton.setCheckable(True)
        self.detailButton.setChecked(True)
        self.detailButton.setObjectName("detailButton")
        self.horizontalLayout.addWidget(self.detailButton)
        self.previousPakageButton = QtWidgets.QPushButton(self.centralwidget)
        self.previousPakageButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(resource_path("icons/left-arrow.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousPakageButton.setIcon(icon3)
        self.previousPakageButton.setObjectName("previousPakageButton")
        self.horizontalLayout.addWidget(self.previousPakageButton)
        self.nextPakageButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextPakageButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(resource_path("icons/right-arrow.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextPakageButton.setIcon(icon4)
        self.nextPakageButton.setObjectName("nextPakageButton")
        self.horizontalLayout.addWidget(self.nextPakageButton)
        self.firstPakageButton = QtWidgets.QPushButton(self.centralwidget)
        self.firstPakageButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(resource_path("icons/up-arrow.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstPakageButton.setIcon(icon5)
        self.firstPakageButton.setObjectName("firstPakageButton")
        self.horizontalLayout.addWidget(self.firstPakageButton)
        self.lastPakageButton = QtWidgets.QPushButton(self.centralwidget)
        self.lastPakageButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(resource_path("icons/down-arrow.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastPakageButton.setIcon(icon6)
        self.lastPakageButton.setObjectName("lastPakageButton")
        self.horizontalLayout.addWidget(self.lastPakageButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.detailedPackageTableView = QtWidgets.QTableView(self.centralwidget)
        self.detailedPackageTableView.setObjectName("detailedPackageTableView")
        self.gridLayout.addWidget(self.detailedPackageTableView, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMouseTracking(False)
        self.line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line.setToolTip("")
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setAutoFillBackground(False)
        self.line.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.packageTableView = QtWidgets.QTableView(self.centralwidget)
        self.packageTableView.setObjectName("packageTableView")
        self.gridLayout.addWidget(self.packageTableView, 1, 0, 1, 2)
        PcapQt.setCentralWidget(self.centralwidget)

        self.retranslateUi(PcapQt)
        self.detailButton.toggled['bool'].connect(self.detailedPackageTableView.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PcapQt)
        PcapQt.setTabOrder(self.startCapture, self.restartButton)
        PcapQt.setTabOrder(self.restartButton, self.previousPakageButton)
        PcapQt.setTabOrder(self.previousPakageButton, self.nextPakageButton)

    def retranslateUi(self, PcapQt):
        _translate = QtCore.QCoreApplication.translate
        PcapQt.setWindowTitle(_translate("PcapQt", "PcapQt"))
        self.startCapture.setToolTip(_translate("PcapQt", "<html><head/><body><p>Start/Stop capturing packages</p></body></html>"))
        self.restartButton.setToolTip(_translate("PcapQt", "<html><head/><body><p>Reset current capture</p></body></html>"))
        self.detailButton.setToolTip(_translate("PcapQt", "<html><head/><body><p>Show/Hide package detail</p></body></html>"))
        self.previousPakageButton.setToolTip(_translate("PcapQt", "<html><head/><body><p>Go to the previous package</p></body></html>"))
        self.nextPakageButton.setToolTip(_translate("PcapQt", "<html><head/><body><p>Go to the next package</p></body></html>"))
        self.firstPakageButton.setToolTip(_translate("PcapQt", "<html><head/><body><p>Go to the first package</p></body></html>"))
        self.lastPakageButton.setToolTip(_translate("PcapQt", "<html><head/><body><p>Go to the last package</p></body></html>"))